server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
jwt:
  token:
    pubKeyPath: D:\project\idea\github\JWT\rsa.pub
    priKeyPath: D:\project\idea\github\JWT\rsa.pri
    secret: J@z!P!.6^J!ia$%#N%$@!-=*&B!
    cookieName: GMALL-TOKEN
    expireTime: 30