server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.128:3306/guli_pms
    username: root
    password: root
  redis:
    host: 127.0.0.1
  rabbitmq:
    addresses: 192.168.211.128
    virtual-host: /jzp
    username: jzp
    password: jzp
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  global-config:
    db-config:
      id-type: auto